### PR TITLE
Now the size is the real disk space

### LINKED ISSUE #11: FilWip is unable to do the correct calculation in terms of size and files number
I noticed that FilWip is doing a wrong calculation of files (in terms of size and number) about the HaikuDepot cache folder: in such folder I have 1664 files for a size of 10,70 MB, but FilWip claims that only 91 files are present, with a total size of 2,82 MB. If I add "RECURSE=yes" to the plugin file for HaikuDepot (since the cache folder of Haiku Depot also contains a folder with Screenshots) the situation is even odd: FilWip will see only 65 file for a total size of 6,33 MB.

See also https://github.com/HaikuArchives/FilWip/issues/6

Screenshot:
image

### PR DESCRIPTION
**Pull request by janus2**
* Should fix #11

### CODE REVIEW

**Comment by janus2** [comment]
## Please test and report!

**Comment by janus2** [comment]
Shall we rename the column "Size" to "Disk space"?

**Comment by humdingerb** [comment]
Up to you. "Size" is short and sweet and the users probably won't care about the technical nuance behind it.

**Comment by humdingerb** [comment]
Looks like the size issue is fixed. At least looking at the HaikuDepot cleaner as described in the #11
 issue. Well done! :)

**Comment by janus2** [comment]
I think there are others bugs in the monitoring looper, but very random and rare.

**Pull request merged**
