### PR TITLE
Modernize the application

### PR DESCRIPTION
**Pull request by janus2**
* Change the custom made tree view with the column list view
* Layout the main window
* Vector icons
* Use Haiku image button and toolbar
* Remove BubbleHelp, use Haiku tootip
* Presets use the plugin name not the position in the tree (this could change)

### CODE REVIEW

**Comment by janus2** [comment]
## WIP please don't merge. This is just for evaluation and suggestions.

**Comment by janus2** [comment]
More changes are coming...

**Comment by janus2** [comment]
### More "classic" take

standard

**Comment by humdingerb** [comment]
I like that, too. What's under "Items"? It those are the Select none/all/needed, maybe "Select" would be better as menu title.

**Comment by humdingerb** [comment]
Or "Selection"?

**Comment by janus2** [comment]
menu

**Comment by janus2** [comment]
I  have used "items" for the "Save preset" MenuItem

**Comment by janus2** [comment]
Items can be confusing, there is a column "Items" Frack!

**Comment by janus2** [comment]
If we call the plugin remover, cleaner or something similar we can put the label over the proper column and name the menu.

**Comment by humdingerb** [comment]
> If we call the plugin remover, cleaner or something similar we can put the label over the proper column and name the menu.

Not sure I understand what you mean here...
How about naming the menu "Selection" with the menu items Select/all/none/needed and "Save as preset".

**Comment by humdingerb** [comment]
> If we call the plugin remover, cleaner or something similar we can put the label over the proper column and name the menu.

Not sure I understand what you mean here...
How about naming the menu "Selection" with the menu items Select/all/none/needed and "Save as preset".

**Comment by janus2** [comment]
I would like to use the same word for the column and the menuItem:

In this example plugin, but with a more specific name:

example

**Comment by humdingerb** [comment]
I'm not sure the casual users know or care that it's implemented via "plugins". They just see different "stuff" they can select to be removed.

**Comment by janus2** [comment]
"In this example plugin, but with a more specific name"

> I'm not sure the casual users know or care that it's implemented via "plugins". They just see different "stuff" they can select to be removed.

Yes, I was thinking something like cleaner, remover...

**Comment by janus2** [comment]
What do you think?

Items -> Selection
Name -> Remove

remove and selection

**Comment by humdingerb** [comment]
+1
Maybe add a bit more padding to the left+right of the separator in the tool bar.
(Personally, I'd also make the icons smaller, like e.g. in BePDF)

**Pull request merged**
